name: "train_clients"

dataset: "camelyon17"
data_root: "/local/scratch/camelyon17/camelyon17_v1.0"
init_model_path: "store/init_models/densenet121.pt"


n_clients: 10
starting_clients: [0,1,2]

mal_clients: [1,3,5,7,8]
fl_attack: "ana"
attack_prob: 0.99
dp_scale: 150

n_rounds: 20
trusted_rounds: 0
n_local_epochs: 1

momentum: 0.9
agg_method: "FedAvgM"

batch_size: 32
seed: 0
arch: "densenet"
trainer: 'densenet121_basic'
num_workers: 8

root_path : "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/"
