
dataset: "camelyon17"
data_root: "/local/scratch/camelyon17/camelyon17_v1.0"

n_clients: 3
n_rounds: 1
n_local_epochs: 1

momentum: 0.9
agg_method: "FedAvgM"

batch_size: 8

arch: "densenet"
trainer: 'densenet121_basic'

local_model_root: "/gris/gris-f/homelv/mkonstan/master_thesis/fedpath/store/clients"
global_model_path: "/gris/gris-f/homelv/mkonstan/master_thesis/fedpath/store/global/global_model.pt"
