name: "train_clients"

dataset: "camelyon17"
data_root: "/local/scratch/camelyon17/camelyon17_v1.0"
init_model_path: "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/init_models/densenet121.pt"


n_clients: 10
starting_clients: [0,1,2,3,4,5,6,7,8,9]

mal_clients: [2,5,8]
fl_attack: "sfa"
attack_prob: 1.0
dp_scale: -1
detector: None

n_rounds: 20
trusted_rounds: 5
n_local_epochs: 1

momentum: 0.7
agg_method: "FedAvgM"

batch_size: 64
seed: 0
arch: "densenet"
trainer: 'densenet121_basic'
num_workers: 8

root_path : "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/"
