name: "train_clients"

dataset: "camelyon17"
data_root: "/local/scratch/camelyon17/camelyon17_v1.0"
init_model_path: "store/init_models/densenet121.pt"

n_clients: 10
mal_clients: [7,8,9]
fl_attack: "ana"
attack_prob: 0.7
dp_scale: 100

n_rounds: 20
n_local_epochs: 5

momentum: 0.9
agg_method: "FedAvgM"

batch_size: 128
seed: 0
arch: "densenet"
trainer: 'densenet121_basic'
num_workers: 8

root_path : "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/"
