experiment:
  global_model_path: "/Users/mirkokonstantin/tud/master-thesis/project/fedpath/store/global/global_model.pt"
  local_model_root: "/Users/mirkokonstantin/tud/master-thesis/project/fedpath/store/clients"
  n_rounds: 1
  n_clients: 3
  arch: 'densenet'
  agg_method: 'FedAvg'
  trainer_class: TrainerClass
  dataset: "camelyon17"
