experiment:
  global_model_path: "/path/to/global/model/weights"
  local_model_root: "/root/path/to/local/models"
  n_rounds: 1
  n_clients: 1
  arch: 'densenet'
  agg_method: 'FedAvg'
  trainer_class: TrainerClass
  dataset: "camelyon17"
