name: "train_clients"

dataset: "camelyon17"
data_root: "/local/scratch/camelyon17/camelyon17_v1.0"
init_model_path: "store/init_models/densenet121.pt"

n_clients: 5
n_mal_clients: 2
fl_attack: "none"
dp_scale: 0

n_rounds: 20
n_local_epochs: 1

momentum: 0.9
agg_method: "FedAvgM"

batch_size: 128
seed: 0
arch: "densenet"
trainer: 'densenet121_basic'
num_workers: 8

root_path : "/gris/gris-f/homestud/melbatel/FedPath/store/"
