name: "train_clients"

dataset: "camelyon17"
data_root: "/local/scratch/camelyon17/camelyon17_v1.0"
init_model_path: "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/init_models/densenet121.pt"


n_clients: 10
starting_clients: [0,1,3,4,6,7,9]

mal_clients: []
fl_attack: "ana"
attack_prob: 0.7
dp_scale: 150

n_rounds: 20
trusted_rounds: 20
n_local_epochs: 1

detector: None

momentum: 0.7
agg_method: "FedAvgM"

batch_size: 64
seed: 0
arch: "densenet"
trainer: 'densenet121_basic'
num_workers: 8

root_path : "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/"
