name: "train_clients"

dataset: "camelyon17"
data_root: "/local/scratch/camelyon17/camelyon17_v1.0"
init_model_path: "store/init_models/densenet121.pt"

n_clients: 10
n_mal_clients: 2
fl_attack: "none"

n_rounds: 20
n_local_epochs: 5

momentum: 0.9
agg_method: "FedAvgM"

batch_size: 8

arch: "densenet"
trainer: 'densenet121_basic'

root_path : "/gris/gris-f/homelv/mkonstan/master_thesis/repo/FedPath/store/"
