name: "train_clients"

dataset: "glas"
data_root: "/local/scratch/glas"
init_model_path: "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/init_models/unet.pt"


n_clients: 3
starting_clients: [0,1,2]

mal_clients: []
fl_attack: "ana"
attack_prob: 0.7
dp_scale: 150

detector: None

n_rounds: 20
trusted_rounds: 3
n_local_epochs: 5

momentum: 0.7
agg_method: "FedAvg"

batch_size: 1
seed: 0
arch: "unet"
trainer: "glas_unet"
num_workers: 8

root_path : "/gris/gris-f/homestud/mikonsta/master-thesis/FedPath/store/"
